### ISSUE TITLE
Being able to compare a roll with static bonus

### ISSUE THREAD

**Issue by mparpaillon** [dice-roller/rpg-dice-roller#236]
First of all, thank you for this awesome lib!

**Is your feature request related to a problem? Please describe.**
I'd like to be able to roll 1d20+3>=15. This would be useful for games like D&D where you have to roll an attack (with your attack modifier) and need to compare to the enemy "armor class" (15 here). Right now it doesn't seem to support it. It works when I remove the (+3)

**Describe the solution you'd like**
I'd like to be able to roll 1d20+3>=15

**Describe alternatives you've considered**
None. I don't know

**Comment by mparpaillon** [comment]
Oh I thought maybe something like this would work but it didn't: (1d20+3)>=15

**Comment by GreenImp** [comment]
Check out group rolls, I think that should do exactly what you're after: https://dice-roller.github.io/documentation/guide/notation/group-rolls.html#target-success-dice-pool-cp

**Comment by mparpaillon** [comment]
Oh ok. I kinda hoped it would work without using a group. I use group rolls to separate actual rolls.
For instance I can write {1d20+3>=15, 1d8+2} to display 2 rolls. The first one tells if the attack succeeded and the second one gives the actual damages.

**Comment by mparpaillon** [comment]
I managed to make it work thanks to you. Thanks again for this awesome lib

**Comment by GreenImp** [comment]
I'm glad you got it working! What did you do in the end?

In regards to the `{1d20+3>=15, 1d8+2}` syntax, it's currently not possible to next group rolls, unfortunately.
So, although `{1d20+3}>=15` works by itself, `{{1d20+3}>=15, 1d8+2}` won't.

It's actually for the same reason that you can't do something like `(4d6)d8`, as mentioned on this ticket: https://github.com/dice-roller/rpg-dice-roller/issues/206#issuecomment-821065811

Hopefully it will be possible in the future though.

**Comment by mparpaillon** [comment]
Well what I used to do was check if the formulas was inside curly braces. If so I stripped the curly braces and split the string on each comma and add the resulting rolls separately in the DB. It was easier for me to have separate rolls. But in the end I don't need the curly braces, I simply split the original formulas on commas and leave the curly braces notation for your Parse.

<img width="532" alt="Capture d’écran 2021-12-17 à 14 13 02" src="https://user-images.githubusercontent.com/1062115/146549825-0b936f94-dbe7-415e-a625-169faeebca43.png">

**Comment by GreenImp** [comment]
That looks good! Sounds like a good way of handling it.
It might be worth bearing in mind that commas can be found inside [Groups Rolls](https://dice-roller.github.io/documentation/guide/notation/group-rolls.html#basic), and [Match Functions](https://dice-roller.github.io/documentation/guide/notation/maths.html#functions).

So it may conflict with splitting on a comma, if you also expect that syntax to be used anywhere.

**Comment by mparpaillon** [comment]
That's right but I don't support Group rolls and math functions. Players can do group rolls by using the comma to separate rolls. Seems good enough for now :)
Thanks again for the awesome lib
