### ISSUE TITLE
Can we / should we make a types declaration file?

### ISSUE THREAD

**Issue by KevinRobertAndrews** [dice-roller/rpg-dice-roller#237]
Hey everyone,

I'm new to using TypeScript with JavaScript projects and I'm wondering if there are plans to create a `.d.ts`? I've never made such a file myself, but I think it would be useful experience to build one out if it makes sense for this project to support TypeScript.

**Comment by JamesSkemp** [comment]
Strange. I had asked about this a while back and I thought definitions got added. At least when I last was able to do dev a few months ago it was working.

Are you not getting TS support when you add it to a project?

**Comment by KevinRobertAndrews** [comment]
@JamesSkemp Ah, whoops my bad. I was just using it incorrectly! Haha, yes I have it working fine now.
