### ISSUE TITLE
Text suffixes to notations

### ISSUE THREAD

**Issue by EuanM** [dice-roller/rpg-dice-roller#248]
AboveVTT uses rpgDiceRoller for manual rolls

Roll20 allows a roll to be labelled, so the vtt knows to feed a roll to, eg, the initiative tracker

I would like to be able to include the purpose of the roll within the rpgDiceRoller notation
so rpgDiceRoller can pass a string to AboveVTT that can tell AboveVTT to either feed the manual roll to the combat tracker, or  display along with the dice roll results

eg
/r 10+3 {tracker}
or
/r 4+2 "Great Axe damage" 
or
/r 1+7 'stealth' 
or
somesuch

Is that already possible?  Would it be a problem for the existing parser if this feature was added?
How would the devteam want the output from such a dice roll to be formatted?

**Comment by GreenImp** [comment]
Is this the same as discussed on this ticket? https://github.com/dice-roller/rpg-dice-roller/issues/222

**Comment by GreenImp** [comment]
As a follow-up of this; There is a branch where what's discussed in #222 is in progress, but not yet complete.
If it is what you're after, I can add syntax for double and single quotes as well. But I think curly braces might conflict with the [Group roll notation](https://dice-roller.github.io/documentation/guide/notation/group-rolls.html).

**Comment by GreenImp** [comment]
I've been making some headway with the description functionality, as mentioned in #222. If you could take a look at this comment: https://github.com/dice-roller/rpg-dice-roller/issues/222#issuecomment-1129337379 and let me know if it's what you're after.
If so, I can look at adding the alternative syntax you've got above.

**Comment by GreenImp** [comment]
As #222 has been resolved, I'm going to mark this as resolved as well.
